# Generated by Django 2.1.7 on 2019-03-13 18:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fournisseurs', '0009_auto_20190313_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saison', models.CharField(max_length=4)),
                ('type_commande', models.CharField(choices=[('IN', 'Initiale'), ('RE', 'Reassort')], max_length=2)),
                ('référence', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('echeance', models.DateField()),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('slug', models.SlugField(unique=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fournisseurs.Fournisseur')),
            ],
        ),
    ]
