# Generated by Django 2.1.7 on 2019-03-13 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='date',
            new_name='date_livraison',
        ),
        migrations.AddField(
            model_name='commande',
            name='commande_livree',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
