# Generated by Django 2.1.7 on 2019-03-13 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_auto_20190313_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='commande_livree',
            field=models.BooleanField(default=False),
        ),
    ]
