# Generated by Django 2.1.7 on 2019-03-13 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0003_auto_20190313_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='slug',
            field=models.SlugField(),
        ),
    ]
