# Generated by Django 2.1.7 on 2019-03-13 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0004_auto_20190313_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='commande_livree',
            new_name='commande_livrée',
        ),
    ]
