# Generated by Django 2.1.5 on 2019-03-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=10)),
                ('pays', models.CharField(max_length=100)),
                ('tva', models.CharField(choices=[('FR', 'France'), ('UE', 'Union Européenne'), ('IN', 'Import')], default='France', max_length=2)),
                ('contact', models.CharField(max_length=100)),
                ('mail_contact', models.EmailField(max_length=254)),
            ],
        ),
    ]
