# Generated by Django 2.1.5 on 2019-03-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='contact',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
