# Generated by Django 2.1.5 on 2019-03-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0002_auto_20190313_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='taux_tva',
            field=models.DecimalField(blank=True, decimal_places=2, default=20, max_digits=4),
            preserve_default=False,
        ),
    ]
