# Generated by Django 2.1.5 on 2019-03-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0003_fournisseur_taux_tva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='adresse',
            field=models.TextField(max_length=100),
        ),
    ]
