# Generated by Django 2.1.5 on 2019-03-13 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0004_auto_20190313_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
