# Generated by Django 2.1.5 on 2019-03-13 17:32

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0006_fournisseur_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fournisseur',
            old_name='name',
            new_name='nom',
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='tva',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
