# Generated by Django 2.1.5 on 2019-03-13 17:37

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0007_auto_20190313_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='pays',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='tva',
            field=models.CharField(choices=[('FR', 'France'), ('UE', 'Union Européenne'), ('IN', 'Import')], max_length=10),
        ),
    ]
