# Generated by Django 2.1.5 on 2019-03-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0008_auto_20190313_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='taux_tva',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
